name: jsonz
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=1.20.1 <2.0.0'

dev_dependencies:
  expect:
    path: /Users/kevmoo/source/github/dart/sdk/pkg/expect
  test: ^0.12.0
